// Command schemagen validates internal/protocol/schema/protocol.schema.json against
// internal/protocol/protocol.go's Op* constants and emits derived artifacts:
//   - internal/protocol/generated.go  (SchemaHash const)
//   - internal/protocol/protocol.d.ts (TS string-union + representative interfaces)
//
// The schema is authoritative (docs/03-protocol.md §11); any intentional break
// requires an ADR and a versioned schema bump. schemagen's only job is to fail
// fast when Go types drift without the schema.
package main

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

var (
	flagSchema = flag.String("schema", "internal/protocol/schema/protocol.schema.json", "path to protocol JSON Schema")
	flagOut    = flag.String("out", "internal/protocol", "output directory for generated artifacts")
)

// opsInGo is the single ground truth for the wire op set as it appears in
// protocol.go's Op* const block. Schemagen mirrors it and asserts equality with
// the schema's definitions/wsOp — duplication is intentional drift detection
// (if we reflected Go AST, a drift could still hide behind build tags).
var opsInGo = []string{
	"init", "add-query", "remove-query", "transact", "error",
	"join-room", "leave-room", "set-presence", "refresh-presence",
	"client-broadcast", "server-broadcast",
	"start-sync", "remove-sync", "refresh-sync-table", "resync-table",
	"start-stream", "append-stream", "subscribe-stream", "unsubscribe-stream",
	"init-ok", "add-query-ok", "add-query-exists", "remove-query-ok",
	"refresh-ok", "transact-ok", "presence", "app-status-changed",
}

func main() {
	flag.Parse()
	schemaPath := *flagSchema
	outDir := *flagOut

	// Allow being invoked from repo root or from tools/schemagen — normalize.
	for _, p := range []string{schemaPath, filepath.Join("..", "..", schemaPath)} {
		if _, err := os.Stat(p); err == nil {
			schemaPath = p
			break
		}
	}
	b, err := os.ReadFile(schemaPath)
	if err != nil {
		fatal("read schema: %v", err)
	}
	h := sha256.Sum256(b)
	hash := hex.EncodeToString(h[:])

	var doc map[string]any
	if err := json.Unmarshal(b, &doc); err != nil {
		fatal("parse schema JSON: %v", err)
	}
	defs, _ := doc["definitions"].(map[string]any)
	wsOpRaw, ok := defs["wsOp"].(map[string]any)
	if !ok {
		fatal("schema missing definitions/wsOp")
	}
	enumAny, _ := wsOpRaw["enum"].([]any)
	var enumVals []string
	for _, v := range enumAny {
		if s, ok := v.(string); ok {
			enumVals = append(enumVals, s)
		}
	}
	sort.Strings(enumVals)
	sortedGo := sortedCopy(opsInGo)
	if !equalStringSlices(enumVals, sortedGo) {
		fatal("wsOp enum drift: schema has %v; Go has %v\n"+
			"Fix by updating definitions/wsOp in the schema and the Op* const block in protocol.go together.", enumVals, sortedGo)
	}
	if err := emitGeneratedGo(outDir, hash); err != nil {
		fatal("emit generated.go: %v", err)
	}
	if err := emitDTS(outDir, enumVals); err != nil {
		fatal("emit d.ts: %v", err)
	}
	fmt.Printf("schemagen: validated %d ops; wrote generated.go (sha=%s…) + protocol.d.ts\n", len(enumVals), hash[:12])
}

func emitGeneratedGo(outDir, hash string) error {
	content := fmt.Sprintf(
		"// Code generated by tools/schemagen; DO NOT EDIT.\n// Source: internal/protocol/schema/protocol.schema.json (sha256:%s)\npackage protocol\n\n// SchemaHash is the sha256 of protocol.schema.json at generation time.\n// A change to the frozen protocol without an ADR is detectable via this const.\nconst SchemaHash = \"sha256:%s\"\n",
		hash, hash,
	)
	return os.WriteFile(filepath.Join(outDir, "generated.go"), []byte(content), 0o644)
}

func emitDTS(outDir string, ops []string) error {
	var b strings.Builder
	b.WriteString("// Code generated by tools/schemagen; DO NOT EDIT.\n")
	b.WriteString("// Source: internal/protocol/schema/protocol.schema.json — mirrors definitions/wsOp + representative shapes.\n\n")
	b.WriteString("export type WsOp =\n")
	for i, op := range ops {
		sep := " |"
		if i == 0 {
			sep = "  "
		}
		b.WriteString(sep + " \"" + op + "\"")
		if i < len(ops)-1 {
			b.WriteString("\n")
		} else {
			b.WriteString(";\n")
		}
	}
	b.WriteString(`
export interface ErrorEnvelope {
  status: number;
  type: string;
  message: string;
  hint?: string;
}

export interface Attr {
  id: string;
  "value-type": "blob" | "ref";
  cardinality: "one" | "many";
  "forward-identity": [string, string, string];
  "reverse-identity"?: [string, string, string] | null;
  "unique?"?: boolean;
  "index?"?: boolean;
  "required?"?: boolean;
  "primary?"?: boolean;
  "on-delete"?: string | null;
  "on-delete-reverse"?: string | null;
  "checked-data-type"?: "string" | "number" | "boolean" | "date" | "json" | null;
}

export type TxStep =
  | ["add-triple",    unknown, unknown, unknown, unknown?]
  | ["deep-merge-triple", unknown, unknown, unknown]
  | ["retract-triple",    unknown, unknown, unknown]
  | ["delete-entity",     unknown, string]
  | ["add-attr",          Attr]
  | ["update-attr",       Record<string, unknown>]
  | ["delete-attr",       string]
  | ["restore-attr",      string]
  | ["rule-params",       Record<string, unknown>];
`)
	return os.WriteFile(filepath.Join(outDir, "protocol.d.ts"), []byte(b.String()), 0o644)
}

func equalStringSlices(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

func sortedCopy(in []string) []string {
	out := append([]string(nil), in...)
	sort.Strings(out)
	return out
}

func fatal(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "schemagen: "+format+"\n", args...)
	os.Exit(1)
}
