// Code generated by cmd/schemagen; DO NOT EDIT.
// Source: internal/protocol/schema/protocol.schema.json (sha256:f91851c1654503c576bea7c3684c4ea7e48412d1ecad4118e8253db6279eaaa9)
package protocol

// SchemaHash is the sha256 of protocol.schema.json at generation time.
// A change to the frozen protocol without an ADR is detectable via this const.
const SchemaHash = "sha256:f91851c1654503c576bea7c3684c4ea7e48412d1ecad4118e8253db6279eaaa9"
