// Code generated by tools/schemagen; DO NOT EDIT.
// Source: internal/protocol/schema/protocol.schema.json (sha256:78eb57b06c1727d0eddfbe28a08077fb9f362aa8802d8f002e605487625054c2)
package protocol

// SchemaHash is the sha256 of protocol.schema.json at generation time.
// A change to the frozen protocol without an ADR is detectable via this const.
const SchemaHash = "sha256:78eb57b06c1727d0eddfbe28a08077fb9f362aa8802d8f002e605487625054c2"
