// Code generated by cmd/schemagen; DO NOT EDIT.
// Source: internal/protocol/schema/protocol.schema.json — mirrors definitions/wsOp + representative shapes.

export type WsOp =
   "add-query"
 | "add-query-exists"
 | "add-query-ok"
 | "app-status-changed"
 | "append-stream"
 | "client-broadcast"
 | "error"
 | "init"
 | "init-ok"
 | "join-room"
 | "leave-room"
 | "presence"
 | "refresh-ok"
 | "refresh-presence"
 | "refresh-sync-table"
 | "remove-query"
 | "remove-query-ok"
 | "remove-sync"
 | "resync-table"
 | "server-broadcast"
 | "set-presence"
 | "start-stream"
 | "start-sync"
 | "subscribe-stream"
 | "transact"
 | "transact-ok"
 | "unsubscribe-stream";

export interface ErrorEnvelope {
  status: number;
  type: string;
  message: string;
  hint?: string;
}

export interface Attr {
  id: string;
  "value-type": "blob" | "ref";
  cardinality: "one" | "many";
  "forward-identity": [string, string, string];
  "reverse-identity"?: [string, string, string] | null;
  "unique?"?: boolean;
  "index?"?: boolean;
  "required?"?: boolean;
  "primary?"?: boolean;
  "on-delete"?: string | null;
  "on-delete-reverse"?: string | null;
  "checked-data-type"?: "string" | "number" | "boolean" | "date" | "json" | null;
}

export type TxStep =
  | ["add-triple",    unknown, unknown, unknown, unknown?]
  | ["deep-merge-triple", unknown, unknown, unknown]
  | ["retract-triple",    unknown, unknown, unknown]
  | ["delete-entity",     unknown, string]
  | ["add-attr",          Attr]
  | ["update-attr",       Record<string, unknown>]
  | ["delete-attr",       string]
  | ["restore-attr",      string]
  | ["rule-params",       Record<string, unknown>];
